name: FeatherShowcase
version: 1.0.0
main: dev.theancientowl.feathershowcase.core.FeatherShowcase
author: AUTHOR
description: Description

api-version: 1.21.1

commands:
  language:
    description: Set prefered language for messages
    usage: /language info/list/[language]
    aliases: [lang]

  feather-reload:
    description: Reload configurations
    usage: /feather-reload {MODULE}
    aliases: [fcreload]

  teleport:
